version: "3"
services:
  elasticsearch:
    image: 'elasticsearch:6.5.1' # use elasticsearch version 6.5.1, latest abailable at this momment
    container_name: iotv_elasticsearch_ln
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - '127.0.0.1:9200:9200'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticlndb:/usr/share/iotv_elasticsearch_ln/data
    
  logstash:
    image: 'logstash:6.5.1'
    container_name: iotv_logstash
    links:
      - elasticsearch

volumes:
  elasticlndb:
    driver: local
